/*jslint newcap: true, browser: true */
/*global module, require*/

module.exports = function (grunt) {
    'use strict';

    var yeomanConfig;

    require('load-grunt-tasks')(grunt);

    // configurable paths
    yeomanConfig = {
        app: '',
        dist: '.dist'
    };

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        yeoman: yeomanConfig,

        bower: {
            dev: {
                dest: 'scripts/vendor',
                js_dest: 'scripts/vendor/js',
                css_dest: 'scripts/vendor/styles',
                options: {
                    stripAffix: true
                }
            }
        },

        // task for cleaning temporary files generated by usemin subtasks (concat, uglify ...)
        clean: {
            dist: ['.tmp', '<%= yeoman.dist %>/*'],
            tmp: '.tmp'
        },

        // prepares usemin task for extracting target files for minification and concatenation tasks from html.
        useminPrepare: {
            html: '<%= yeoman.app %>/index.html',
            options: {
                dest: '<%= yeoman.app %>'
            }
        },

        // task for copying assets to the dist folder
        copy: {
            dist: {
                files: [{
                    expand: true,
                    dot: true,
                    cwd: '<%= yeoman.app %>',
                    dest: '<%= yeoman.dist %>',
                    src: [
                        'assets/{,*/}*.*',
                        'index.html'
                    ]
                }]
            }
        },

        htmlmin: {
            dist: {
                options: {
                    removeComments: true,
                    collapseWhitespace: true
                },

                files: [{
                    expand: true,
                    cwd: '<%= yeoman.app %>',
                    dest: '<%= yeoman.dist %>',
                    src: [
                        'views/{,*/}*.*'
                    ]
                }]
            }
        },

        // less task for compiling less files to css
        less: {
            dist: {
                options: {
                    compress: true,
                    cleancss: true
                },

                files: {
                    '<%= yeoman.dist %>/styles/styles.min.css': '<%= yeoman.dist %>/styles/main.less'
                }
            },
            app: {
                options: {
                    compress: false,
                    cleancss: false
                },

                files: {
                    '<%= yeoman.app %>/styles/styles.css': '<%= yeoman.app %>/styles/main.less'
                }
            },
            minify: {
                options: {
                    compress: true,
                    cleancss: true
                },

                files: {
                    '<%= yeoman.app %>/styles/styles.min.css': '<%= yeoman.app %>/styles/main.less'
                }
            }
        },

        // uglify task, mangle false (because angular)
        uglify: {
            options: {
                mangle: false
            }
        },

        // task for setting html to reference the transformed js and css files.
        usemin: {
            html: '<%= yeoman.dist %>/index.html',
            options: {
                blockReplacements: {
                    less: function (block) {
                        return '<link rel="stylesheet" type="text/css" href="' + block.dest + '">';
                    }
                }
            }
        }
    });

    grunt.registerTask('default', [
        'clean:tmp',
        'bower',
        'less:app'
    ]);

    grunt.registerTask('production', [
        'clean:dist',
        'useminPrepare',
        'less:dist',
        'concat:generated',
        'uglify:generated',
        'cssmin:generated',
        'htmlmin:dist',
        'copy',
        'usemin'
    ]);
};